library(geojsonio)
library(sp)
library(rgdal)
library(rgeos)
library(dplyr)
setwd("Github/Census 2011/geojson manipulation/")
map = readOGR("2011sa4.geojson", "OGRGeoJSON")
data <- read.csv("/home/shannon/Documents/ABS/2011/data/2011_BCP_SA4_for_AUST_short-header/2011 Census BCP Statistical Areas Level 4 for AUST/AUST/2011Census_B01_AUST_SA4_short.csv") %>% select(region_id,Tot_P_P,Tot_P_M,Tot_P_F)
joined <- merge(map, data, by.x="SA4_CODE", by.y="region_id")
geojson_write(joined, file = "sa4population.geojson")
